package com.Knowvex.Enums;

public enum ProductEnum {
    AI,
    ML,
    DATA_SCIENCE,
    WEB_DEVELOPMENT,
    CYBER_SECURITY,
    IOT_ROBOTICS,
    CLOUD_COMPUTING,
    HYBRID_ELECTRIC_VEHICLE,
    AUTO_CAD,
    DIGITAL_MARKETING,
    FINANCE,
    HUMAN_RESOURCE,
    C_CPLUSPLUS,
    PYTHON,
    JAVA;
}
