version: '3.8'

services:
  nextjs:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"  # Next.js will run on port 3000
    environment:
      - NODE_ENV=development  # Set environment to development for hot-reloading
    volumes:
      - .:/app  # Mount the current directory to the /app directory inside the container
      - /app/node_modules  # Ensure node_modules is not overridden
    command: "npm run dev"  # Run the Next.js development server
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Link the Nginx config
    depends_on:
      - nextjs
    networks:
      - webnet

networks:
  webnet:
